version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
    steps:
      - run:
         command: choco --confirm install msys2
         shell: cmd.exe
      - run:
         command: C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start -c "pacman --sync --noconfirm python"
         shell: cmd.exe
      - run:
         command: C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start -c "python -c 'import os; print(os.name)'"
         shell: cmd.exe
         